### PR TITLE
Manage other library dirs

### LINKED ISSUE #8: Manage other library dirs too
Currently, we only support the default library location `~/.steam/steam/steamapps` or the one pointed at by the `STEAM_APPS_DIR` environment variable.
Supporting other library locations specified in the configuration files would be optimal.

### PR DESCRIPTION
**Pull request by 414n**
Closes #8

### CODE REVIEW

**Comment by 414n** [comment]
@triffid may I ask you to try out this branch?
I'd like to know if it works in your setup too, especially if you've got nothing installed under the default steamapps dir in `~/.steam/steam/steamapps`.
You can run the script by using `make run`.

**Comment by triffid** [comment]
```
~/Projects/protonsh [1] $ make run
STEAMLIB=src/fun/steamlib.sh STEAMAWK=src/fun/steamlib.awk bash src/bin/protonsh.sh
DEBUG: steam_find_libraries: start
DEBUG: evaluating /home/triffid/.steam/steam/
DEBUG: found steamapps dir /home/triffid/.steam/steam/steamapps
DEBUG: evaluating /mnt/storage/Homes/triffid/Private/Software/Steam
DEBUG: found steamapps dir /mnt/storage/Homes/triffid/Private/Software/Steam/steamapps
DEBUG: Found 2 steamapps dirs: /home/triffid/.steam/steam/steamapps /mnt/storage/Homes/triffid/Private/Software/Steam/steamapps
DEBUG: steam_find_libraries: end
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
List of proton prefixes found in Steam:
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
0) 17390        Spore
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
1) 238010       Deus Ex: Human Revolution - Director's Cut
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
2) 292030       The Witcher 3: Wild Hunt
Choice?
```

```
$ l ~/.steam/steam/steamapps/common/
total 0
drwxr-xr-x 1 triffid users 288 Nov 16 21:31 Proton 5.0
drwxr-xr-x 1 triffid users 270 Jan 17 15:38 Proton 5.13
drwxr-xr-x 1 triffid users  26 May 23  2020 Steamworks Shared
```

Looks good, just gotta fix your `find` invocation ;)

**Comment by 414n** [comment]
@triffid indeed, I must fix those `find` lines :+1: 
Thank you very much for your test! Did you run it with no/empty `~/.config/protonsh` file?
These changes should render the override of `STEAM_APPS_DIR` inside that file useless.

**Comment by triffid** [comment]
```
$ rm ~/.config/protonsh
$ make run
STEAMLIB=src/fun/steamlib.sh STEAMAWK=src/fun/steamlib.awk bash src/bin/protonsh.sh
DEBUG: steam_find_libraries: start
DEBUG: evaluating /home/triffid/.steam/steam/
DEBUG: found steamapps dir /home/triffid/.steam/steam/steamapps
DEBUG: evaluating /mnt/storage/Homes/triffid/Private/Software/Steam
DEBUG: found steamapps dir /mnt/storage/Homes/triffid/Private/Software/Steam/steamapps
DEBUG: Found 2 steamapps dirs: /home/triffid/.steam/steam/steamapps /mnt/storage/Homes/triffid/Private/Software/Steam/steamapps
DEBUG: steam_find_libraries: end
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
List of proton prefixes found in Steam:
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
0) 17390        Spore
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
1) 238010       Deus Ex: Human Revolution - Director's Cut
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
2) 292030       The Witcher 3: Wild Hunt
Choice?
```

**Comment by 414n** [comment]
Great!
I just pushed a couple of changes that should silence those warnings. If you'd like, try them too, otherwise I'm already happy about the outcome ;-)

**Comment by triffid** [comment]
```
$ git pull
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 17 (delta 7), reused 17 (delta 7), pack-reused 0
Unpacking objects: 100% (17/17), 1.59 KiB | 148.00 KiB/s, done.
From github.com:414n/protonsh
362376e..9f90446  8-other-library-dirs -> origin/8-other-library-dirs
Updating 362376e..9f90446
Fast-forward
src/bin/protonsh.sh  | 4 ++--
src/fun/steamlib.awk | 2 ++
src/fun/steamlib.sh  | 2 +-
3 files changed, 5 insertions(+), 3 deletions(-)

$ make run
STEAMLIB=src/fun/steamlib.sh STEAMAWK=src/fun/steamlib.awk bash src/bin/protonsh.sh
DEBUG: steam_find_libraries: start
DEBUG: evaluating /home/triffid/.steam/steam/
DEBUG: found steamapps dir /home/triffid/.steam/steam/steamapps
DEBUG: evaluating /mnt/storage/Homes/triffid/Private/Software/Steam
DEBUG: found steamapps dir /mnt/storage/Homes/triffid/Private/Software/Steam/steamapps
DEBUG: Found 2 steamapps dirs: /home/triffid/.steam/steam/steamapps /mnt/storage/Homes/triffid/Private/Software/Steam/steamapps
DEBUG: steam_find_libraries: end
List of proton prefixes found in Steam:
0) 17390        Spore
1) 238010       Deus Ex: Human Revolution - Director's Cut
2) 292030       The Witcher 3: Wild Hunt
```

nice :)

**Comment by 414n** [comment]
Perfect! Thank you very much!

**Comment by triffid** [comment]
Thanks for pinging me :D

**Pull request merged**
